services:
  tdoescher\CokibanBundle\EventListener\GetPageLayoutListener:
    autoconfigure: true
  tdoescher\CokibanBundle\EventListener\ParseFrontendTemplateListener:
    autoconfigure: true
  tdoescher\CokibanBundle\EventListener\ReplaceInsertTagsListener:
    autoconfigure: true
